submodules:
- - 1. What is BCS?
  - - Definitions
  - - Ten Questions
  - - Antecedents
    - - Philosophy
    - - Scientific Revolution
    - - Early Science
    - - Behaviroism
  - - Mind & Brain
    - - Cognitive Revolution
    - - Early Neuroscience
    - - Remaining Questions
  - - Defining BCS
    - - Neuroscience
    - - Cognitive Psych
    - - Cog Neuro
    - - Computational Approaches
    - - Interdisciplinary BCS
  - - The Two Track Mind
- - 2. Philosophy of Mind & Brain
  - - Goals and Methods
  - - History of Philosophy
  - - Philosophy of Mind
  - - Philosophy of BCS

misc:
- - Homework
  - - Homework 1
    - Homework 2
- - Readings
  - - Readings 1
    - Readings 2